import ScrollAnimation from "@/component/animatedCard";
import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ashim Raj Shrestha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="icon" href="/favicon.ico" type="image/x-icon" sizes="any" /> */}
      </head>
      <body className={inter.className}>
        <div className="preloader"></div>
        <header className="navigation">
          <div className="container">
            <div className="logo">Logo</div>
            <div className="routes">
              <Link href="#" className="navLink">
                Home
              </Link>
              <Link href="#" className="navLink">
                About
              </Link>
              <Link href="#" className="navLink">
                Works
              </Link>
              <Link href="#" className="navLink">
                Contact
              </Link>
            </div>
            <Link className="letsTalk" href="#">
              Let's talk
            </Link>
          </div>
        </header>
        <main className="main">{children}</main>
        <footer className="footer">
          <div className="container">footer</div>
        </footer>
      </body>
    </html>
  );
}
